version: '3.9'


services:

  #### DATABASE CONTAINER####
  mysql:
    image: mariadb
    container_name: database_srv
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
    -  MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    -  MYSQL_DATABASE=${DB_WORDPRESS}
    -  MYSQL_USER=${MYSQL_DB_USER}
    -  MYSQL_PASSWORD=${MYSQL_DB_PASSWORD}
    restart: unless-stopped



  #### CONTANER WORDPRESS ####
  wordpress:
    image: wordpress:php7.4-fpm-alpine
    container_name: php
    volumes:
      - ./data/html:/var/www/html
    depends_on:
      - mysql
    environment:
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DB_HOST: mysql
    -  MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    -  WORDPRESS_DB_NAME=${DB_WORDPRESS}
    -  WORDPRESS_DB_USER=${MYSQL_DB_USER}
    -  WORDPRESS_DB_PASSWORD=${MYSQL_DB_PASSWORD}

    links:
      - mysql
    restart: unless-stopped


  #### NGINX CONTAINER ####
  nginx:
    image: nginx:latest
    container_name: web_srv
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./data/html:/var/www/html
    ports:
      - 8080:80
    links:
      - wordpress
      - prometheus
      - grafana


  ### PHPMYADMIN CONTAINER####
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_srv
    restart: always
    links:
      - mysql:mysql
    environment:
    -  MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}


  #### PROMETHEUS CONTAINER ####
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_srv
    volumes:
      - ./data/prometheus:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    restart: unless-stopped
    ports:
      - 9090:9090
  #### GRAFANA CONTAINER ####
  grafana:
    image: grafana/grafana
    container_name: grafana_srv
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: unless-stopped

  #### NODE-EXPORTER CONTAINER #####
  node-exporter:
    image: prom/node-exporter
    container_name: node_exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - 9100:9100
    restart: unless-stopped
    deploy:
      mode: global

